apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketpool-validator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rocketpool-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.service.labels }}
{{ toYaml . | nindent 4 }}
{{- end }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "rocketpool-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
{{- if .Values.service.ports.api.enabled }}
    - name: api
      port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
      protocol: TCP
{{- end }}
{{- if .Values.service.ports.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.ports.metrics.port }}
      targetPort: {{ .Values.service.ports.metrics.targetPort }}
      protocol: TCP
{{- end }}
